// <auto-generated />
using System;
using Microsoft.EntityFrameworkCore;
using Microsoft.EntityFrameworkCore.Infrastructure;
using Microsoft.EntityFrameworkCore.Migrations;
using Microsoft.EntityFrameworkCore.Storage.ValueConversion;
using RecImage.Repositories;

#nullable disable

namespace RecImage.Migrations
{
    [DbContext(typeof(RepositoryContext))]
    [Migration("20220120172329_ImageInfoRevision")]
    partial class ImageInfoRevision
    {
        protected override void BuildTargetModel(ModelBuilder modelBuilder)
        {
#pragma warning disable 612, 618
            modelBuilder
                .HasAnnotation("ProductVersion", "6.0.1")
                .HasAnnotation("Relational:MaxIdentifierLength", 64);

            modelBuilder.Entity("RecImage.Models.ImageInfo", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    b.Property<DateTime>("Creation")
                        .HasColumnType("datetime(6)");

                    b.Property<string>("Extension")
                        .HasColumnType("longtext");

                    b.Property<string>("ImageHash")
                        .HasColumnType("longtext");

                    b.Property<int>("ImageUserId")
                        .HasColumnType("int");

                    b.Property<bool>("IsUploaded")
                        .HasColumnType("tinyint(1)");

                    b.Property<string>("Name")
                        .HasColumnType("longtext");

                    b.HasKey("Id");

                    b.HasIndex("ImageUserId");

                    b.ToTable("ImageInfo");

                    b.HasData(
                        new
                        {
                            Id = 1,
                            Creation = new DateTime(2022, 1, 20, 18, 23, 29, 686, DateTimeKind.Local).AddTicks(9613),
                            Extension = "jpg",
                            ImageHash = "hashhashhash",
                            ImageUserId = 1,
                            IsUploaded = false,
                            Name = "ladybug"
                        },
                        new
                        {
                            Id = 2,
                            Creation = new DateTime(2022, 1, 20, 18, 23, 29, 686, DateTimeKind.Local).AddTicks(9648),
                            Extension = "jpg",
                            ImageHash = "hashhashhash",
                            ImageUserId = 1,
                            IsUploaded = false,
                            Name = "frog"
                        },
                        new
                        {
                            Id = 3,
                            Creation = new DateTime(2022, 1, 20, 18, 23, 29, 686, DateTimeKind.Local).AddTicks(9651),
                            Extension = "jpg",
                            ImageHash = "hashhashhash",
                            ImageUserId = 1,
                            IsUploaded = false,
                            Name = "pepe"
                        });
                });

            modelBuilder.Entity("RecImage.Models.User", b =>
                {
                    b.Property<int>("UserId")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    b.Property<string>("Login")
                        .HasColumnType("longtext");

                    b.HasKey("UserId");

                    b.ToTable("Users");

                    b.HasData(
                        new
                        {
                            UserId = 1,
                            Login = "kamil@crustacean.pl"
                        },
                        new
                        {
                            UserId = 2,
                            Login = "limak@naecatsurc.lp"
                        });
                });

            modelBuilder.Entity("RecImage.Models.ImageInfo", b =>
                {
                    b.HasOne("RecImage.Models.User", "ImageUser")
                        .WithMany("Images")
                        .HasForeignKey("ImageUserId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.Navigation("ImageUser");
                });

            modelBuilder.Entity("RecImage.Models.User", b =>
                {
                    b.Navigation("Images");
                });
#pragma warning restore 612, 618
        }
    }
}
